name: Create Tag

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Klemensas/action-autotag@380682c329fccb8b270e70e59d40d0e918dc5a0f
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
