# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Node.js Package

on:
  push:
    tags: # This triggers the workflow on any newly created tag
      - '*'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }} # if needed
      - with:
          cmd: build
        uses: borales/actions-yarn@v4
      - uses: borales/actions-yarn@v4
        with:
          cmd: test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }} # if needed
      - with:
          cmd: build
        uses: borales/actions-yarn@v4
      - with:
          cmd: publish
        uses: borales/actions-yarn@v4
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
